### ISSUE TITLE
[HELP] Step by step installation guide 

### ISSUE THREAD

**Issue by xe1os** [counterstrikesharp-panel/css-bans#102]
Hi,

Can someone please help in sharing the steps on installing on a linux machine. 

I have referred the docs but that didn't help me enough on setting up the panel.

It will be really helpful if detailed steps are provided.

Thanks.

**Comment by hobsRKM** [comment]
https://docs.cssbans.online/apache-setup-guide

**Comment by xe1os** [comment]
@hobsRKM i tried all the steps shared in the apache setup guide.

Getting below message in the browser.

![image](https://github.com/user-attachments/assets/b6d29abd-8bad-4bb1-b1ab-bb399be2216a)
