### ISSUE TITLE
Logging system overhaul

### ISSUE THREAD

**Issue by hks27d** [counterstrikesharp-panel/css-bans#104]
Hello!

I believe the logging system requires a complete overhaul. In instances of platform crashes, no logs are being stored in the designated `storage/logs` directory. I previously encountered difficulties during initial setup (#103). I was able to resolve them independently, but other users might not be so fortunate. The platform is currently failing to provide essential log information in specific cases.

**Comment by hobsRKM** [comment]
if you dont see logs, you have folde permission issue to storage/logs.

**Comment by hks27d** [comment]
> if you dont see logs, you have folder permission issue to storage/logs.

Hi,
Thank you for answering!

I'm afraid it doesn't have anything to do with permissions. I had no logs for this situation (#103). After fixing the issue myself (by adding quotation marks), the logs started to appear. Therefore, I assure you that I had no permission issues to storage/logs, as you mentioned above.
The logging system must provide info for these general issues. At the present moment it doesn't.
