### ISSUE TITLE
i follow the docker guide but got permission denied

### ISSUE THREAD

**Issue by LaplaceTor** [counterstrikesharp-panel/css-bans#117]
![屏幕截图 2024-09-05 171955](https://github.com/user-attachments/assets/13bf4db6-ee85-473c-b75f-63f0c1ade58a)

**Comment by hobsRKM** [comment]
> ![屏幕截图 2024-09-05 171955](https://private-user-images.githubusercontent.com/28674126/364709025-13bf4db6-ee85-473c-b75f-63f0c1ade58a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzEzNDYsIm5iZiI6MTcyNTUzMTA0NiwicGF0aCI6Ii8yODY3NDEyNi8zNjQ3MDkwMjUtMTNiZjRkYjYtZWU4NS00NzNjLWI3NWYtNjNmMGMxYWRlNThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwMTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiM2Y4OTZkZTNlMTM4YTRjZDgyZWJjMjhmZDRkMWY1MWJmOTU0MDg5YTZmNGFkZDk3Yzg5ZWMyYjczOWIwOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AgCJvM02J8OsvmAcyOn1NMAfyYvU08Ai7-IpOqgTfTw)

give full permission to storage folder (777)

**Comment by LaplaceTor** [comment]
> 
> give full permission to storage folder (777)

![屏幕截图 2024-09-05 182421](https://github.com/user-attachments/assets/c3170a0e-20fe-401b-97fe-ffc13d7cfa10)

Still bugly

**Comment by hobsRKM** [comment]
Not a panel issue problem is with they way ur using docker and it doesn’t seems to work on ur host bcoz of ur host file perms issue
