### ISSUE TITLE
[BUG] When muting a player it shows 2h on the website

### ISSUE THREAD

**Issue by HerrMagiic** [counterstrikesharp-panel/css-bans#127]
Mute a player for like 2mins. It now shows on the website 2h

Database
![image](https://github.com/user-attachments/assets/f1f893ed-9926-47ab-937e-dc8d57db5c91)

![image](https://github.com/user-attachments/assets/16d546ab-4023-4703-bfbc-21044c571a23)

**Comment by HerrMagiic** [comment]
web

**Comment by originalaidn** [comment]
hmm, weird. maybe timezone issue. i can't answer to this :/

**Comment by hobsRKM** [comment]
> web

the server app and ur timezone should match, refer the guide on timezone
