### ISSUE TITLE
[BUG] Support for the new Weapon Paints scheme

### ISSUE THREAD

**Issue by HerrMagiic** [counterstrikesharp-panel/css-bans#128]
The weapon paints plugin has a new DB scheme. You are also now able to add charms and stickers.
Would be great if we get support for this aswell

**Comment by originalaidn** [comment]
Soon (maybe this weekend) the site will support those.

**Comment by hobsRKM** [comment]
https://github.com/counterstrikesharp-panel/css-bans/releases/tag/5.0_beta
