### ISSUE TITLE
Error occurred during Steam authentication.

### ISSUE THREAD

**Issue by Neko-Miaoo** [counterstrikesharp-panel/css-bans#135]
![屏幕截图 2024-12-09 195209](https://github.com/user-attachments/assets/567be1e1-6711-446a-a5f5-7073d96d5fa9)

**Comment by hobsRKM** [comment]
use https domain

**Comment by Neko-Miaoo** [comment]
It still didn't work

**Comment by Neko-Miaoo** [comment]
finished!
thanks!
