### ISSUE TITLE
Feature Request: Multiple Database support

### ISSUE THREAD

**Issue by HerrMagiic** [counterstrikesharp-panel/css-bans#36]
Would it be possible to add support for multiple databases?

I have created a separate database for each plugin, with its own user accounts, to ensure that plugins can only access the information they need and cannot interact with anything else.

Specifically, I would like to request additional database support for the following plugins:
- Weapon Skins Plugin
- K4-System Plugin

This enhancement would greatly improve security and data isolation. Thank you!

**Comment by hobsRKM** [comment]
https://github.com/counterstrikesharp-panel/css-bans/releases/tag/3.2

This is now available as part of this release.
