### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by cristiantwx** [counterstrikesharp-panel/css-bans#54]
Here I leave the updated file with the Spanish translations, I corrected some errors that there were with some translations and I also added lines of things that did not even have a word, the first name of the object directly appeared.

It would be nice to be able to translate more things in the panel, such as:

Select type of knife
Create new group
Add VIP
Action buttons like edit and delete vip
Some fill fields
The description of the flags

[es.json](https://github.com/user-attachments/files/15805622/es.json)

**Comment by cristiantwx** [comment]
I also forgot to add, being able to translate the word "Wear" when selecting a weapon skin or when selecting a knife skin

**Comment by originalaidn** [comment]
Wear is added into Skin as i know
Others will be added asap & when i have free time

**Comment by cristiantwx** [comment]
> Wear is added into Skin as i know Others will be added asap & when i have free time

I could only translate Wear in the glove selection, in the others I couldn't

**Comment by cristiantwx** [comment]
Update:

[es.json](https://github.com/user-attachments/files/15807023/es.json)

**Comment by originalaidn** [comment]
everything is added in #62 so you can close it
