### ISSUE TITLE
Can't connect to RCON server: Connection refused

### ISSUE THREAD

**Issue by BigTwoProduction** [counterstrikesharp-panel/css-bans#56]
Hello,

I've been following your work for a few weeks now, very impressive, many thanks!
All works before there is the possibility of connections to multiple database, I had managed by creating views in the base simple admin. Anyway, I'm opening this issue because I can't place an RCON command, it's returning "Can't connect to RCON server: Connection refused".

Here are my server launch parameters:

./cs2 -dedicated -console -usercon -ip 90.17.115.139 -port 27115 -maxplayers 12 +net_public_adr '90.17.115.139 ' +sv_setsteamaccount ******0853XX +game_type 0 +game_mode 1 +mapgroup mg_active +map de_inferno +tv_enable 1 +tv_port 27120 +tv_maxclients 10 exec autoexec.cfg

Where XXX.XXX.XXX.XXX is my public IP. The only port open are 27115/27120 for this VM.

Have you had this problem before, or am I the only one?

Best Regards,
Jordan.

**Comment by BigTwoProduction** [comment]
The "hack" to have a working rcon throught CSS-BANS panel is to start server with local IP:

./cs2 -dedicated -console -usercon -ip 192.168.1.40 -port 27115 -maxplayers 12 +net_public_adr '90.17.115.139 ' +sv_setsteamaccount ******0853XX +game_type 0 +game_mode 1 +mapgroup mg_active +map de_inferno +tv_enable 1 +tv_port 27120 +tv_maxclients 10 exec autoexec.cfg

But CSS-BANS sync server with local IP, so connect bouton not working.
![image](https://github.com/counterstrikesharp-panel/css-bans/assets/19799334/278cbea5-0ccf-41ff-b85b-9422c9e94c01)

I this case i just edit indatabase the ip for the detected server (192.168.1.40) to (90.17.115.139) and after start and stop the server, after i mask the second server with 192.168.1.40
![image](https://github.com/counterstrikesharp-panel/css-bans/assets/19799334/98b974da-acac-47b6-9a46-008c12a5bacc)

This is the normal way ?
Best Regard

**Comment by hobsRKM** [comment]
> 90.17.115.139

Ensure ur all TCP ports are open for web operations especiall RCON Port of 27015 which is tcp and is not blocking from ur firewall.

**Comment by hobsRKM** [comment]
> Hello,
> 
> My server CS2 is on 27115 port because my old CS:GO server is on 27015 port. For this server, the CS2 ports 27115 and 27120 ports are open TCP/UDP. So do you confirm i need for css-bans to open for CS2 27015 port ?
> 
> Best Regards, Jordan.

open up all ur TCP ports from firewall and check which one works, keep those.
