### ISSUE TITLE
Global ban share

### ISSUE THREAD

**Issue by tuljko188** [counterstrikesharp-panel/css-bans#6]
Hello

as discussed on Discord channel, I'd like to suggest a feature, similar/the same as it was on SourceBans / Material Admin:
When an admin bans a player on server A, it gets banned on all other servers pegged to the database, considering that all server ID's / IPs are in the same database

This enhancement has to be on owner's choice while installing - if he wants to keep it enabled or disabled whenever he wants, so when it stops - ban gets pegged only to the server where he got banned

regards (rptr7 discord)

**Comment by hobsRKM** [comment]
This option now is added on the latest version of simpleadmin 1.4
You have a config to set it to true for this option to work. Panel will have now no changes as you have a work arround. This will be de-prioritized for now.
