### ISSUE TITLE
Error SQL Inital setup

### ISSUE THREAD

**Issue by BigTwoProduction** [counterstrikesharp-panel/css-bans#61]
Hello,

I found a mistake, there is a ',' missing in this file storage/app/cssbans.sql
So user can't finalise install of CSS-Bans
[Line ](https://github.com/counterstrikesharp-panel/css-bans/blob/8adc25af93309df746f8fe1d8c39d0f30c9d66e1/storage/app/cssbans.sql#L121)

I add it in my side, can your make correction on your side ?

Best Regards,
Jordan.

**Comment by hobsRKM** [comment]
Thanks, fixed.
