### ISSUE TITLE
Image not Found - CS Rating bug

### ISSUE THREAD

**Issue by BigTwoProduction** [counterstrikesharp-panel/css-bans#68]
Hello,

With last update there is some bug came with CS Rating :
![image](https://github.com/counterstrikesharp-panel/css-bans/assets/19799334/18dbc633-5747-4dbd-89e5-962ef4c143a5)

Website try to load this asset : https://exemple.fr/cs2/cs2images/ratings/rating.common.png
CSS-Bans is in my side in a subfolder named "cs2".

Best regards,
Jordan.

**Comment by hobsRKM** [comment]
> Hello,
> 
> With last update there is some bug came with CS Rating : ![image](https://private-user-images.githubusercontent.com/19799334/340348481-18dbc633-5747-4dbd-89e5-962ef4c143a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzYzNDEsIm5iZiI6MTcxODYzNjA0MSwicGF0aCI6Ii8xOTc5OTMzNC8zNDAzNDg0ODEtMThkYmM2MzMtNTc0Ny00ZGJkLTg5ZTUtOTYyZWY0YzE0M2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE0NTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNjdlMTQzOWRjMTZlMjBjYjgwMTdjOWUwMDg5NjMyYjM5ZTI3NDc2YmFmNDkxNDJjYTQyODYxYmViY2I0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u7LrSAwIv5KQHXum40qt4N7VPXFaGiacoiVvogAq6h8)
> 
> Website try to load this asset : https://exemple.fr/cs2/cs2images/ratings/rating.common.png CSS-Bans is in my side in a subfolder named "cs2".
> 
> Best regards, Jordan.

re download the release

**Comment by BigTwoProduction** [comment]
I did, when a put the "update", i unzip all archive in the subfolder and copy old .env above the new one.

![image](https://github.com/counterstrikesharp-panel/css-bans/assets/19799334/28d6b44b-09f7-466e-b2b8-fa638d39d308)

I think there is an other problem. 
The subfolder seem to be and twice form cs2rating.

Did i make a mistake ?

**Comment by BigTwoProduction** [comment]
my .env : 

VITE_SITE_DIR=/cs2
APP_URL=https://big-two.fr
STEAM_REDIRECT_URI=${APP_URL}/cs2/auth/steam/callback
ASSET_URL=https://big-two.fr/cs2
