### ISSUE TITLE
Image not Found - CS Rating bug (Real Bug don't close)

### ISSUE THREAD

**Issue by BigTwoProduction** [counterstrikesharp-panel/css-bans#70]
Hello,

I search more information to explain.
According to comment in .env, it's write 

```
VITE_SITE_DIR= #Should  start with / and must not end with / EX: /bans leave blank if site is being setup in root folder of web
ASSET_URL=     #Should not end with / EX: https://mysite.com/bans
```

So my css-bans is in subdirectory, not in my root folder website https://big-two.fr, it's in /cs in my side
So .env should be:
```
VITE_SITE_DIR= /cs2
ASSET_URL=  https://big-two.fr/cs2
```

And in /app/Helpers/CommonHelper.php, there is two different way to return the resultat of fonction getCSRatingImage and getCSRankImage.

getCSRatingImage can not work instead of getCSRankImage.

```
fonction getCSRatingImage
        return '<span class="cs2rating-text-' . $classRating . '">'.$score.'</span><img src="' . asset(getAppSubDirectoryPath().$imagePath) . '" class="cs2rating" alt="CS Rating">';

function getCSRankImage
        return '<img src="' . asset($imagePath) . '" class="cs2rating" alt="CS Rating">';
```
In the fonction getCSRatingImage you use getAppSubDirectoryPath() added to $imagePath. 
Fonction getAppSubDirectoryPath() read value of VITE_SITE_DIR in .env

So when you use getAppSubDirectoryPath() for getCSRatingImage you concatenate twice the value of VITE_SITE_DIR, once in ASSET_URL and once in VITE_SITE_DIR.

Or in getCSRankImage you don't use getAppSubDirectoryPath(), so i can see the image of getCSRankImage. 
exemple url
getCSRankImage : https://big-two.fr/cs2/images/ratings/3.png
getCSRatingImage : https://big-two.fr/cs2/cs2images/ratings/rating.common.png

Can you confirm i'm right ?

Best regard,
Jordan.

**Comment by hobsRKM** [comment]
I think u haven’t re downloaded the release . Re download the release as mentioned
