### ISSUE TITLE
[REQ] Menu Servers option

### ISSUE THREAD

**Issue by crashzk** [counterstrikesharp-panel/css-bans#73]
It would be interesting to have the Servers option in the menu, something similar to what we had in sourcebans.

https://bans.scrap.tf/index.php?p=servers&s=0
https://bans.panda-community.com/index.php?p=servers

So when I click on the Servers option I open a page with all servers and we can click on the servers listed so we can see players, map, IP, gametracker banner perhaps.

![image](https://github.com/counterstrikesharp-panel/css-bans/assets/32937653/cded50f8-1e88-4f65-b013-dbf1374c84ef)

So even if you are logged in as admin, you can apply direct punishments, bans, kicks, comms.

**Comment by hobsRKM** [comment]
> It would be interesting to have the Servers option in the menu, something similar to what we had in sourcebans.
> 
> https://bans.scrap.tf/index.php?p=servers&s=0 https://bans.panda-community.com/index.php?p=servers
> 
> So when I click on the Servers option I open a page with all servers and we can click on the servers listed so we can see players, map, IP, gametracker banner perhaps.
> 
> ![image](https://private-user-images.githubusercontent.com/32937653/340808480-cded50f8-1e88-4f65-b013-dbf1374c84ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDQ3NjYsIm5iZiI6MTcxODgwNDQ2NiwicGF0aCI6Ii8zMjkzNzY1My8zNDA4MDg0ODAtY2RlZDUwZjgtMWU4OC00ZjY1LWIwMTMtZGJmMTM3NGM4NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzNDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZDFjOTFkYTYyOWE4MDMwNDRhY2JjMTc5NmYwMzRjYjVhNzljMzFjOTM4NTRlNDFiMzNiMzFlNjAwZDRkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BOv5GT1YHdBpRFpjbSrteH2Ri2s0LCd97lGa47QhiQ)
> 
> So even if you are logged in as admin, you can apply direct punishments, bans, kicks, comms.

on dashbord click on eye icon. Live punishment exists. Login as admin.
