### ISSUE TITLE
admin edit button

### ISSUE THREAD

**Issue by brkvlr** [counterstrikesharp-panel/css-bans#8]
I go to the edit section to include the previously added administrator in the newly added server, but there is an individual server selection, I do not see the All Server option there.

And favicon can be added for the site :)

**Comment by hobsRKM** [comment]
1) To enhance server management efficiency, administrators can add and select few servers, each with unique permissions. Choosing to "Select All" lacks purpose in this scenario for edit. Instead, it's more effective for administrators to individually add servers via the "Add" option and assign permissions accordingly. Allowing blanket access to all servers would compromise the flexibility to tailor permissions to each server's specific needs. Therefore, the functionality to select multiple servers at once is restricted.

2) Favicon exists.

**Comment by brkvlr** [comment]
1. When we add a new server to the system, admin is not included under the name of all servers, that's why I wrote it. I add it again by adding a new admin. If you think it is unnecessary, no problem. I'm waiting for the group update, good work!!
