### ISSUE TITLE
500 Server Error on Approve/Reject Ban Appeal Action

### ISSUE THREAD

**Issue by HerrMagiic** [counterstrikesharp-panel/css-bans#80]
#### Description
When clicking on "Approve" or "Reject" for a ban appeal, the application redirects to the following URL: `https://bans.orizon-surf.de/appeals/5/status`. However, this results in a 500 Server Error.

#### Steps to Reproduce
1. Navigate to a ban appeal.
2. Click on "Approve" or "Reject".
3. Observe the redirect to `https://bans.orizon-surf.de/appeals/5/status`.
4. Note the 500 Server Error.

**Comment by hobsRKM** [comment]
check the logs, may be u have incorrect email settings.
