### ISSUE TITLE
Invisible Servers Appearing in Report Player Dropdown

### ISSUE THREAD

**Issue by HerrMagiic** [counterstrikesharp-panel/css-bans#81]
#### Description
When reporting a player, the dropdown menu allows the selection of servers. Despite being marked as invisible in the settings, these servers are still appearing in the list.

#### Steps to Reproduce
1. Go to the "Report Player" page.
2. Open the server selection dropdown.
3. Note that servers marked as invisible in the settings are still visible.

#### Expected Behavior
The servers only marked as visible should appear in the server selection dropdown.

#### Screenshots
- **Server Selection Dropdown:**
  ![image](https://github.com/counterstrikesharp-panel/css-bans/assets/70164539/ca6ead6c-b574-4f76-a7e9-384142fd8cb1)
  
- **Settings Showing Invisible Servers:**
  ![image](https://github.com/counterstrikesharp-panel/css-bans/assets/70164539/45165c6e-5831-489e-bf38-f8289be2dd14)

**Comment by hobsRKM** [comment]
fixed
