### ISSUE TITLE
[BUG] Failed to unban player

### ISSUE THREAD

**Issue by ghostt187** [counterstrikesharp-panel/css-bans#82]
Fails to unban player if an admin is given access web only
![image-1](https://github.com/counterstrikesharp-panel/css-bans/assets/147412694/93c98033-d8e3-4336-8211-d9138ac0ef79)
![image](https://github.com/counterstrikesharp-panel/css-bans/assets/147412694/4824e508-7df6-480c-b97a-7102854d2e29)

**Comment by hobsRKM** [comment]
fixed
