### ISSUE TITLE
Panel Admin and K4system

### ISSUE THREAD

**Issue by SubCoderHUN** [counterstrikesharp-panel/css-bans#98]
Hello!

The problem is as follows:
When I provide my "Panel Admin" steam-id during the site installation, after the installation is complete and I log into the site, it logs me in as a regular user. I cannot manage the site and do not have access to anything.

Another problem:
If I provide the K4system database information in the .env file and try to load the site, I get a 500 server error.
Otherwise, the WeaponPaints module works properly.

Debug informations:
[https://flareapp.io/share/bP9b29k7](https://flareapp.io/share/bP9b29k7)
**(My Steam ID is not correct. In debug, SteamID is 76561198957302190. In reality, mine is 76561198957302193.)**

The essential content of the .env file is here, although the login details are not real but very similar.

```
RANKS="Enabled"

DB_HOST_RANKS=host
DB_DATABASE_RANKS=p3726_RANKS
DB_USERNAME_RANKS=a3726_mXvUerTpG6
DB_PASSWORD_RANKS=hX7VGZZzcwPNjfQ_RGxW=kLf
DB_PORT_RANKS=3306
```

![kép_2024-07-29_225831977](https://github.com/user-attachments/assets/8bd118fc-b1a6-4135-b4b4-34c9bfeab521)
![kép_2024-07-29_230939335](https://github.com/user-attachments/assets/e65dea29-6662-40a9-9c43-a7f3f6411fd2)

**Comment by hobsRKM** [comment]
user error - installtion error 
Steam error is ur id issue. GIve admin from game server.

Read docs carefully.Docs does not mention to change ranks on .env. its managed form modules.
